In [4]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
import seaborn as sns
sns.set()

In [5]:
data = pd.read_csv(r'C:\Users\prakh\Downloads\real_estate_price_size_year (1).csv')

In [6]:
data

price     size  year
0   234314.144   643.09  2015
1   228581.528   656.22  2009
2   281626.336   487.29  2018
3   401255.608  1504.75  2015
4   458674.256  1275.46  2009
..         ...      ...   ...
95  252460.400   549.80  2009
96  310522.592  1037.44  2009
97  383635.568  1504.75  2006
98  225145.248   648.29  2015
99  274922.856   705.29  2006

[100 rows x 3 columns]

In [32]:
x = data[['size','year']]
y = data['price']

In [33]:
scaler = StandardScaler()

In [34]:
scaler.fit(x,y)

StandardScaler()

In [35]:
scaler.transform(x)

array([[-0.70816415,  0.51006137],
       [-0.66387316, -0.76509206],
       [-1.23371919,  1.14763808],
       [ 2.19844528,  0.51006137],
       [ 1.42498884, -0.76509206],
       [-0.937209  , -1.40266877],
       [-0.95171405,  0.51006137],
       [-0.78328682, -1.40266877],
       [-0.57603328,  1.14763808],
       [-0.53467702, -0.76509206],
       [ 0.69939906, -0.76509206],
       [ 3.33780001, -0.76509206],
       [-0.53467702,  0.51006137],
       [ 0.52699137,  1.14763808],
       [ 1.51100715, -1.40266877],
       [ 1.77668568, -1.40266877],
       [-0.54810263,  1.14763808],
       [-0.77276222, -1.40266877],
       [-0.58004747, -1.40266877],
       [ 0.58943055,  1.14763808],
       [-0.78365788,  0.51006137],
       [-1.02322731,  0.51006137],
       [ 1.19557293,  0.51006137],
       [-1.12884431,  0.51006137],
       [-1.10378093, -0.76509206],
       [ 0.84424715,  1.14763808],
       [-0.95171405,  1.14763808],
       [ 1.62279723,  0.51006137],
       [-0.58004747,

In [36]:
x_scaled = pd.DataFrame(scaler.transform(x), columns = ['size','year'])

In [37]:
x_scaled

size      year
0  -0.708164  0.510061
1  -0.663873 -0.765092
2  -1.233719  1.147638
3   2.198445  0.510061
4   1.424989 -0.765092
..       ...       ...
95 -1.022856 -0.765092
96  0.622084 -0.765092
97  2.198445 -1.402669
98 -0.690623  0.510061
99 -0.498347 -1.402669

[100 rows x 2 columns]

In [38]:
reg = LinearRegression()

In [39]:
reg.fit(x_scaled,y)

LinearRegression()

In [40]:
reg.score(x_scaled,y) #R squared

0.7764803683276793

In [41]:
reg.intercept_ # constant

292289.4701599997

In [42]:
reg.coef_ # coef of size and year

array([67501.57614152, 13724.39708231])

In [43]:
reg_summary = pd.DataFrame([['Intercept'],['prize'],['year']],columns = ['Features'])

In [44]:
reg_summary['Weights'] = reg.intercept_,reg.coef_[0],reg.coef_[1]

In [45]:
reg_summary

Features        Weights
0  Intercept  292289.470160
1      prize   67501.576142
2       year   13724.397082

In [46]:
predicted  = reg.predict(x_scaled)

In [47]:
predicted

array([251487.55831903, 236976.55857112, 224762.12124518, 447688.27618312,
       377978.03540671, 209775.60239038, 235047.5566597 , 220165.59235875,
       269156.95675102, 245697.50127961, 328999.58170971, 507095.80467165,
       263198.21324064, 343612.85900293, 375034.05120339, 392967.77046502,
       271042.3198222 , 220876.01902325, 233884.5688127 , 347827.60181061,
       246391.61320635, 230220.29855474, 379992.81228669, 223090.98481576,
       207282.09020001, 365028.12432233, 243797.91264021, 408831.12544674,
       260135.63675424, 445777.86601799, 308857.3520032 , 233884.5688127 ,
       223697.04476541, 224782.80216104, 309068.36244145, 255656.57311692,
       266249.96820132, 208650.76017159, 269890.15350093, 264056.64546025,
       337754.30386831, 269156.95675102, 275000.32418183, 391330.41348571,
       355250.64965125, 264056.64546025, 231732.60790333, 237805.57751871,
       249233.31986436, 245558.22808068, 252491.71908521, 337754.30386831,
       320253.59190728, 2

In [50]:
predicteddf = pd.DataFrame(predicted,columns = ['Predicted Price'])

In [51]:
predicteddf

Predicted Price
0     251487.558319
1     236976.558571
2     224762.121245
3     447688.276183
4     377978.035407
..              ...
95    212744.633688
96    323780.678136
97    421437.208242
98    252671.602760
99    239399.483497

[100 rows x 1 columns]